### ISSUE TITLE
Chrome Warning about touchstart event

### ISSUE THREAD

**Issue by damiencuvillier** [AnthonyNahas/ngx-long-press2#1]
For a few months now, I've got this warning in my JS console when using ngx-longpress2. 
![image](https://user-images.githubusercontent.com/3856306/148793590-8e816a0f-76e3-4696-96e8-1771338ee712.png)

Topic is related [to this](https://github.com/angular/angular/issues/8866)

**Comment by AnthonyNahas** [comment]
hi @damiencuvillier thanks for reaching out!

do you have any idea how to fix that?

**Comment by AnthonyNahas** [comment]
@damiencuvillier If you are still facing this issue please consider to reopen this ticket

thank you
