### ISSUE TITLE
Support for Angular 16?

### ISSUE THREAD

**Issue by jdupuis** [AnthonyNahas/ngx-long-press2#5]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
Will this be upgraded to support Angular 16 ? Thanks a lot !

**Comment by i-rme** [comment]
As I believe the module works well on Angular 16 without any change, @AnthonyNahas should publish a new version announcing compatibility with Angular 16.

Meanwhile, if you want to use it with Angular 16 you can just copy the module and directive from https://github.com/AnthonyNahas/ngx-long-press2/tree/master/projects/ngx-long-press2/src/lib to your project and just yolo it.

**Comment by AnthonyNahas** [comment]
I will update this lib to v16. Just give me few minutes

**Comment by AnthonyNahas** [comment]
https://www.npmjs.com/package/ngx-long-press2 v5 is now live

thank you

**Comment by jdupuis** [comment]
Thanks a lot @AnthonyNahas ! 👍
